#!/bin/bash

echo "Backup config xmonad, xmobar, fish, alacritty"

cp ~/.xmonad/xmonad.hs ./dotfiles/.xmonad/
cp ~/.config/xmobar/xmobarrc ./dotfiles/.config/xmobar/
cp -r ~/.config/fish ./dotfiles/.config/
cp ~/.config/alacritty/alacritty.yml ./dotfiles/.config/alacritty/
# cp ~/.config/xfce4/xfconf .dotfiles/.config/xfce4/
