#!/bin/bash

#Yay
sudo pacman -Sy
git clone https://aur.archlinux.org/yay.git && cd yay/ && makepkg -si --noconfirm && cd .. && rm -rf yay/

yay -S --needed --noconfirm $(cat bin/pkg | egrep -v "^\s*(#|$)")

sh install/app.sh
sh install/vim.sh
sh install/config.sh
