#!/bin/bash

sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist
sudo pacman -Syy
git clone https://aur.archlinux.org/yay.git && cd yay/ && makepkg -si --noconfirm && cd .. && rm -rf yay/

yay -S --needed --noconfirm $(cat bin/pkg | egrep -v "^\s*(#|$)")

sh install/app.sh
sh install/config.sh
sh install/vim.sh

sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg
