#!/bin/bash

sudo true
bash ./WinToGrub
until git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si --noconfirm && cd .. && rm -rf yay-bin; do
  rm -rf yay-bin
  sleep 1
done

until yay -Sy --needed --batchinstall --removemake --nodiffmenu $(cat base | egrep -v "^\s*(#|$)"); do
  sleep 1
done

stow xmonad
# Change all scripts in .local/bin to be executable.
find $HOME/.local/bin -type f -print0 | xargs -0 chmod 775
xmonad --recompile

sudo chsh $USER -s "/bin/zsh"

sudo systemctl enable ly

git clone https://github.com/hmanhng/dotfile.git ~/dotfiles && cd ~/dotfiles && ./install.sh zsh alacritty
