#!/bin/bash

git config --global user.email "$USER@icloud.com"
git config --global user.name "$USER"

#Bamboo
cat tmp/bamboo.txt | doas tee -a /etc/profile
env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['xkb:us::eng', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"

doas sed -i 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf

cp -rf dotfiles/. $HOME/
doas cp -rf $HOME/etc/* /etc && rm -rf $HOME/etc
doas cp -rf $HOME/usr/* /usr && rm -rf $HOME/usr
stow xmonad

wget -q --show-progress https://github.com/NyaMisty/AltServer-Linux/releases/download/v0.0.5/AltServer-x86_64 -O ~/.local/bin/AltServer-x86_64

# Wallpapers
# git clone https://github.com/hmanhng/Wallpapers.git $HOME/Pictures/Wallpapers

# Fonts ms
# git clone https://github.com/hmanhng/WindowsFonts.git $HOME/WindowsFonts && rm -rf $HOME/WindowsFonts/.git && doas mv $HOME/WindowsFonts/ /usr/share/fonts/ && doas chmod 644 /usr/share/fonts/WindowsFonts/* && fc-cache --force

# Change all scripts in .local/bin to be executable.
find $HOME/.local/bin -type f -print0 | xargs -0 chmod 775
xmonad --recompile

doas chsh $USER -s "/bin/zsh"

doas systemctl enable ly
doas systemctl enable betterlockscreen@$USER
doas systemctl enable bluetooth
doas systemctl enable systemd-timesyncd
doas systemctl enable clash-core-service@$USER

doas usermod -aG video $USER # Permission for light
echo "ideapad_laptop" | doas tee -a /etc/modules
doas bash -c 'echo 259:2 > /sys/power/resume'
doas mkinitcpio -P
doas grub-mkconfig -o /boot/grub/grub.cfg

git clone https://github.com/hmanhng/dotfile.git ~/dotfiles && cd ~/dotfiles && ./install.sh zsh alacritty
