#!/bin/bash

git config --global user.email "$USER@icloud.com"
git config --global user.name "$USER"

#Bamboo
cat tmp/bamboo.txt | sudo tee -a /etc/profile
env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['xkb:us::eng', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"

sudo sed -i 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf

cp -rf dotfiles/. $HOME/
sudo cp -rf $HOME/etc/* /etc && rm -rf $HOME/etc
sudo cp -rf $HOME/usr/* /usr && rm -rf $HOME/usr

wget -q --show-progress https://github.com/NyaMisty/AltServer-Linux/releases/download/v0.0.5/AltServer-x86_64 -O ~/.local/bin/AltServer-x86_64

# Wallpapers
# git clone https://github.com/hmanhng/Wallpapers.git $HOME/Pictures/Wallpapers

# Fonts ms
# git clone https://github.com/hmanhng/WindowsFonts.git $HOME/WindowsFonts && rm -rf $HOME/WindowsFonts/.git && sudo mv $HOME/WindowsFonts/ /usr/share/fonts/ && sudo chmod 644 /usr/share/fonts/WindowsFonts/* && fc-cache --force

sudo systemctl enable betterlockscreen@$USER
sudo systemctl enable bluetooth
sudo systemctl enable systemd-timesyncd
sudo systemctl enable clash-core-service@$USER

sudo usermod -aG video $USER # Permission for light
echo "ideapad_laptop" | sudo tee -a /etc/modules
sudo bash -c 'echo 259:2 > /sys/power/resume'
sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg

